name: Build and Test

on: [push, pull_request, pull_request_review]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build collection
        run: ansible-galaxy collection build
      - name: Update pip
        run: python3 -m pip install --upgrade pip
      - name: Install pyyaml
        run: python3 -m pip install pyyaml
      - name: Get collection version
        run: python3 get_version.py
      - name: Store collection version in bash
        run: echo "::set-env name=COLLECTION_VERSION::$(cat version)"
      - name: Install collection
        run: ansible-galaxy collection install alliedtelesis-awplus-${COLLECTION_VERSION}.tar.gz

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ansible_collections/alliedtelesis/awplus
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set awplus and ansible env vars
        run: |
          echo "::set-env name=AWPLUS::${GITHUB_WORKSPACE}/ansible_collections/alliedtelesis/awplus/"
          echo "::set-env name=ANSIBLE_PATH::${GITHUB_WORKSPACE}/ansible"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install ansible-test
        run: |
          sudo apt update
          sudo apt-get install build-essential libssl-dev libffi-dev python-dev
          git clone https://github.com/ansible/ansible.git ${GITHUB_WORKSPACE}/ansible
          pip install --upgrade pip
          pip install setuptools
          pip install -r ${GITHUB_WORKSPACE}/ansible/requirements.txt
          pip install -r ${GITHUB_WORKSPACE}/ansible/test/units/requirements.txt
          pip install -r ${AWPLUS}/requirements.txt
          source ${ANSIBLE_PATH}/hacking/env-setup
      - name: Test unit tests
        run: |
          cd ${AWPLUS}
          ${ANSIBLE_PATH}/bin/ansible-test units --python ${{ matrix.python-version }}
